apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-deployment
  labels:
    app: label-order-deployment
spec:
  replicas: 2
  template:
    metadata:
      name: order-app
      labels:
        app: label-order-app
    spec:
      containers:
        - name: order-container
          image: "amigoscode/kubernetes:order-v1"
          ports:
            - containerPort: 8081
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
  selector:
    matchLabels:
      app: label-order-app
---
apiVersion: v1
kind: Service
metadata:
  name: order-cluster-ip-service
spec:
  selector:
    app: label-order-app
  ports:
    - port: 80
      targetPort: 8081
  type: ClusterIP